### ISSUE TITLE
NotImplementedError: Converter is not implemented

### ISSUE THREAD

**Issue by Matrixmax** [ENOT-AutoDL/onnx2torch#152]
File "/home/www/anaconda3/envs/gplsn/lib/python3.7/site-packages/onnx2torch/node_converters/registry.py", line 69, in get_converter
    raise NotImplementedError(f'Converter is not implemented ({description})')
NotImplementedError: Converter is not implemented (OperationDescription(domain='', operation_type='Dropout', version=7))

onnx2torch==1.5.6

**Comment by JohnMasoner** [comment]
Hey @Matrixmax ,

Could you provide your onnx model?

Actually, `Dropout` is implemented in  `onnx2torch` . You could find it at [Operators](https://github.com/ENOT-AutoDL/onnx2torch/blob/main/operators.md)

**Comment by Matrixmax** [comment]
I used matlab to write this model which has 4 conv layers and 2 fc layers.
[Bench_sub_net_1_1_.onnx.zip](https://github.com/ENOT-AutoDL/onnx2torch/files/10988332/Bench_sub_net_1_1_.onnx.zip)

**Comment by JohnMasoner** [comment]
Hey @Matrixmax ,

Thanks for you provided you onnx model.

In fact, onnx2torch does support the Dropout operation, but it doesn't support version 7 yet. I temporarily resolved this issue by registering version 7.

But i got the new problem, the Flatten is Version 1 in your onnx model.

I think a better solution would be to modify the operator version. However, since I am not familiar with MATLAB, I cannot provide you with a direct solution.

Here is my temporary solution to the problem(Obviously, this is not a good way):
1. change the `/home/www/anaconda3/envs/gplsn/lib/python3.7/site-packages/onnx2torch/node_converters/dropout.py` in the 30th.

```python
@add_converter(operation_type='Dropout', version=10)
@add_converter(operation_type='Dropout', version=7)
def _(node: OnnxNode, graph: OnnxGraph) -> OperationConverterResult:  # pylint: disable=unused-argument
    node_attributes = node.attributes
    ratio = node_attributes.get('ratio', 0.5)
```

**Comment by Matrixmax** [comment]
I tried the method you said and got the same result as you (flatten version 1).
Thanks for your timely answer, I decided to modify my matlab code (or rewrite the matlab part with PyTorch).
Sincere thanks to you.
